override_admin_theme:
    resource: "@OverrideAdminThemeBundle/Resources/config/routing.yml"
    prefix:   /

override_fos_user:
    resource: "@OverrideFOSUserBundle/Resources/config/routing.yml"
    prefix:   /

unique_password:
    resource: "@UniquePasswordBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
