<?php

namespace UniquePasswordBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{

    public function findNumberOfPasswords($name)
    {
        return $this->getEntityManager()
                        ->createQuery(
                                'SELECT count(p) FROM UniquePasswordBundle:Content p, UniquePasswordBundle:Category c WHERE p.category = :name'
                        )
                        ->setParameter('name', $name)
                        ->getResult();
    }

}
