unique_password_dashboard:
    path:     /
    defaults: { _controller: UniquePasswordBundle:Dashboard:index }

unique_password_add:
    path:     /password/add
    defaults: { _controller: UniquePasswordBundle:Password:add }
    methods: [GET]

unique_password_add_new:
    path:     /password/add
    defaults: { _controller: UniquePasswordBundle:Password:addNew }
    methods: [POST]

unique_password_list:
    path:     /password
    defaults: { _controller: UniquePasswordBundle:Password:list }

unique_categories_list:
    path:     /categories
    defaults: { _controller: UniquePasswordBundle:Category:list }
    
unique_categories_getlist:
    path:     /categories/get
    defaults: { _controller: UniquePasswordBundle:Category:getList }
