unique_password_dashboard:
    path:     /
    defaults: { _controller: UniquePasswordBundle:Dashboard:index }

unique_password_add:
    path:     /password/add
    defaults:
        _controller:  FrameworkBundle:Template:template
        template:     'UniquePasswordBundle:Password:add.html.twig'
        maxAge:       86400
        sharedAge:    86400

unique_password_add_new:
    path:     /password/add
    defaults: { _controller: UniquePasswordBundle:Password:addNew }
    methods: [POST]

unique_password_update_new:
    path:     /password/update/{id}
    defaults: { _controller: UniquePasswordBundle:Password:update, id: 0 }
    methods: [POST]

unique_password_list:
    path:     /password
    defaults:
        _controller:  FrameworkBundle:Template:template
        template:     'UniquePasswordBundle:Password:retrieve.html.twig'
        maxAge:       86400
        sharedAge:    86400

unique_password_getlist:
    path:     /password/get
    defaults: { _controller: UniquePasswordBundle:Password:getList }

unique_password_view:
    path:     /password/view/{id}
    defaults: { _controller: UniquePasswordBundle:Password:view }

unique_password_getcontent:
    path:     /password/getContent/{id}
    defaults: { _controller: UniquePasswordBundle:Password:getContent, id: 0 }

unique_categories_list:
    path:     /categories
    defaults:
        _controller:  FrameworkBundle:Template:template
        template:     'UniquePasswordBundle:Category:categories.html.twig'
        maxAge:       86400
        sharedAge:    86400

unique_categories_getlist:
    path:     /categories/get
    defaults: { _controller: UniquePasswordBundle:Category:getList }
