services:
    unique_password.mycrypt:
        class: UniquePasswordBundle\Helper\MyCrypt

#    unique_password.example:
#        class: UniquePasswordBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
