services:
    unique_password.mycrypt:
        class: UniquePasswordBundle\Helper\MyCrypt

    unique_password.createcontent:
        class: UniquePasswordBundle\Helper\CreateContent
        arguments: ['@service_container', '@doctrine.orm.entity_manager', '@logger']

